### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by binjospookie** [alexeyvax/SwipeSlideshow#1]
It could be better to listen click on `input[type="radio"]`.

Before
```
ol > li
```
Ater 
```
ol > li > input[type="radio"]
```

**Comment by alexeyvax** [comment]
I added input with type radio in li element, but I'm not sure that you wanted it. If I misunderstood you, please indicate what you wanted.

**Comment by binjospookie** [comment]
Cool. You understood right! TY
